export const mobileNumberCodes = [
    { "id": 1, "code": "+1", "name": "United States", "flag": "🇺🇸" },
    { "id": 2, "code": "+1", "name": "Canada", "flag": "🇨🇦" },
    { "id": 3, "code": "+61", "name": "Australia", "flag": "🇦🇺" },
    { "id": 4, "code": "+65", "name": "Singapore", "flag": "🇸🇬" },
    { "id": 5, "code": "+63", "name": "Philippines", "flag": "🇵🇭" },
    { "id": 6, "code": "+244", "name": "Angola", "flag": "🇦🇴" },
    { "id": 7, "code": "+1 264", "name": "Anguilla", "flag": "🇦🇮" },
    { "id": 8, "code": "+1268", "name": "Antigua and Barbuda", "flag": "🇦🇬" },
    { "id": 9, "code": "+54", "name": "Argentina", "flag": "🇦🇷" },
    { "id": 10, "code": "+374", "name": "Armenia", "flag": "🇦🇲" },
    { "id": 11, "code": "+297", "name": "Aruba", "flag": "🇦🇼" },
    { "id": 12, "code": "+213", "name": "Algeria", "flag": "🇩🇿" },
    { "id": 13, "code": "+43", "name": "Austria", "flag": "🇦🇹" },
    { "id": 14, "code": "+994", "name": "Azerbaijan", "flag": "🇦🇿" },
    { "id": 15, "code": "+1 242", "name": "Bahamas", "flag": "🇧🇸" },
    { "id": 16, "code": "+973", "name": "Bahrain", "flag": "🇧🇭" },
    { "id": 17, "code": "+880", "name": "Bangladesh", "flag": "🇧🇩" },
    { "id": 18, "code": "+1 246", "name": "Barbados", "flag": "🇧🇧" },
    { "id": 19, "code": "+375", "name": "Belarus", "flag": "🇧🇾" },
    { "id": 20, "code": "+32", "name": "Belgium", "flag": "🇧🇪" },
    { "id": 21, "code": "+501", "name": "Belize", "flag": "🇧🇿" },
    { "id": 22, "code": "+229", "name": "Benin", "flag": "🇧🇯" },
    { "id": 23, "code": "+1 441", "name": "Bermuda", "flag": "🇧🇲" },
    { "id": 24, "code": "+975", "name": "Bhutan", "flag": "🇧🇹" },
    { "id": 25, "code": "+591", "name": "Bolivia", "flag": "🇧🇴" },
    { "id": 26, "code": "+387", "name": "Bosnia and Herzegovina", "flag": "🇧🇦" },
    { "id": 27, "code": "+267", "name": "Botswana", "flag": "🇧🇼" },
    { "id": 28, "code": "+55", "name": "Brazil", "flag": "🇧🇷" },
    { "id": 29, "code": "+246", "name": "British Indian Ocean Territory", "flag": "🇮🇴" },
    { "id": 30, "code": "+1 284", "name": "British Virgin Islands", "flag": "🇻🇬" },
    { "id": 31, "code": "+673", "name": "Brunei Darussalam", "flag": "🇧🇳" },
    { "id": 32, "code": "+359", "name": "Bulgaria", "flag": "🇧🇬" },
    { "id": 33, "code": "+226", "name": "Burkina Faso", "flag": "🇧🇫" },
    { "id": 34, "code": "+257", "name": "Burundi", "flag": "🇧🇮" },
    { "id": 35, "code": "+855", "name": "Cambodia", "flag": "🇰🇭" },
    { "id": 36, "code": "+237", "name": "Cameroon", "flag": "🇨🇲" },
    { "id": 37, "code": "+355", "name": "Albania", "flag": "🇦🇱" },
    { "id": 38, "code": "+55", "name": "Canary Islands", "flag": "🇮🇨" },
    { "id": 39, "code": "+238", "name": "Cape Verde", "flag": "🇨🇻" },
    { "id": 40, "code": "+1345", "name": "Cayman Islands", "flag": "🇰🇾" },
    { "id": 41, "code": "+236", "name": "Central African Republic", "flag": "🇨🇫" },
    { "id": 42, "code": "+235", "name": "Chad", "flag": "🇹🇩" },
    { "id": 43, "code": "+56", "name": "Chile", "flag": "🇨🇱" },
    { "id": 44, "code": "+86", "name": "China", "flag": "🇨🇳" },
    { "id": 45, "code": "+57", "name": "Colombia", "flag": "🇨🇴" },
    { "id": 46, "code": "+269", "name": "Comoros", "flag": "🇰🇲" },
    { "id": 47, "code": "+242", "name": "Congo-Brazzaville", "flag": "🇨🇬" },
    { "id": 48, "code": "+243", "name": "Congo-Kinshasa", "flag": "🇨🇩" },
    { "id": 49, "code": "+682", "name": "Cook Islands", "flag": "🇨🇰" },
    { "id": 50, "code": "+506", "name": "Costa Rica", "flag": "🇨🇷" },
    { "id": 51, "code": "+385", "name": "Croatia", "flag": "🇭🇷" },
    { "id": 52, "code": "+53", "name": "Cuba", "flag": "🇨🇺" },
    { "id": 53, "code": "+599", "name": "Curacao", "flag": "🇨🇼" },
    { "id": 54, "code": "+357", "name": "Cyprus", "flag": "🇨🇾" },
    { "id": 55, "code": "+420", "name": "Czech Republic", "flag": "🇨🇿" },
    { "id": 56, "code": "+45", "name": "Denmark", "flag": "🇩🇰" },
    { "id": 57, "code": "+253", "name": "Djibouti", "flag": "🇩🇯" },
    { "id": 58, "code": "+1 767", "name": "Dominica", "flag": "🇩🇲" },
    { "id": 59, "code": "+1 849", "name": "Dominican Republic", "flag": "🇩🇴" },
    { "id": 60, "code": "+593", "name": "Ecuador", "flag": "🇪🇨" },
    { "id": 61, "code": "+20", "name": "Egypt", "flag": "🇪🇬" },
    { "id": 62, "code": "+503", "name": "El Salvador", "flag": "🇸🇻" },
    { "id": 63, "code": "+240", "name": "Equatorial Guinea", "flag": "🇬🇶" },
    { "id": 64, "code": "+291", "name": "Eritrea", "flag": "🇪🇷" },
    { "id": 65, "code": "+372", "name": "Estonia", "flag": "🇪🇪" },
    { "id": 66, "code": "+268", "name": "Eswatini", "flag": "🇸🇿" },
    { "id": 67, "code": "+251", "name": "Ethiopia", "flag": "🇪🇹" },
    { "id": 68, "code": "+298", "name": "Faroe Islands", "flag": "🇫🇴" },
    { "id": 69, "code": "+679", "name": "Fiji", "flag": "🇫🇯" },
    { "id": 70, "code": "+358", "name": "Finland", "flag": "🇫🇮" },
    { "id": 71, "code": "+33", "name": "France", "flag": "🇫🇷" },
    { "id": 72, "code": "+594", "name": "French Guiana", "flag": "🇬🇫" },
    { "id": 73, "code": "+689", "name": "French Polynesia", "flag": "🇵🇫" },
    { "id": 74, "code": "+241", "name": "Gabon", "flag": "🇬🇦" },
    { "id": 75, "code": "+220", "name": "Gambia", "flag": "🇬🇲" },
    { "id": 76, "code": "+995", "name": "Georgia", "flag": "🇬🇪" },
    { "id": 77, "code": "+49", "name": "Germany", "flag": "🇩🇪" },
    { "id": 78, "code": "+233", "name": "Ghana", "flag": "🇬🇭" },
    { "id": 79, "code": "+350", "name": "Gibraltar", "flag": "🇬🇮" },
    { "id": 80, "code": "+30", "name": "Greece", "flag": "🇬🇷" },
    { "id": 81, "code": "+299", "name": "Greenland", "flag": "🇬🇱" },
    { "id": 82, "code": "+1 473", "name": "Grenada", "flag": "🇬🇩" },
    { "id": 83, "code": "+590", "name": "Guadeloupe", "flag": "🇬🇵" },
    { "id": 84, "code": "+1 671", "name": "Guam", "flag": "🇬🇺" },
    { "id": 85, "code": "+502", "name": "Guatemala", "flag": "🇬🇹" },
    { "id": 86, "code": "+224", "name": "Guinea", "flag": "🇬🇳" },
    { "id": 87, "code": "+245", "name": "Guinea-Bissau", "flag": "🇬🇼" },
    { "id": 88, "code": "+592", "name": "Guyana", "flag": "🇬🇾" },
    { "id": 89, "code": "+509", "name": "Haiti", "flag": "🇭🇹" },
    { "id": 90, "code": "+504", "name": "Honduras", "flag": "🇭🇳" },
    { "id": 91, "code": "+852", "name": "Hong Kong SAR", "flag": "🇭🇰" },
    { "id": 92, "code": "+36", "name": "Hungary", "flag": "🇭🇺" },
    { "id": 93, "code": "+354", "name": "Iceland", "flag": "🇮🇸" },
    { "id": 94, "code": "+91", "name": "India", "flag": "🇮🇳" },
    { "id": 95, "code": "+62", "name": "Indonesia", "flag": "🇮🇩" },
    { "id": 96, "code": "+98", "name": "Iran", "flag": "🇮🇷" },
    { "id": 97, "code": "+964", "name": "Iraq", "flag": "🇮🇶" },
    { "id": 98, "code": "+353", "name": "Ireland", "flag": "🇮🇪" },
    { "id": 99, "code": "+44", "name": "Isle of Man", "flag": "🇮🇲" },
    { "id": 100, "code": "+972", "name": "Israel", "flag": "🇮🇱" },
    { "id": 101, "code": "+39", "name": "Italy", "flag": "🇮🇹" },
    { "id": 102, "code": "+1 876", "name": "Jamaica", "flag": "🇯🇲" },
    { "id": 103, "code": "+81", "name": "Japan", "flag": "🇯🇵" },
    { "id": 104, "code": "+962", "name": "Jordan", "flag": "🇯🇴" },
    { "id": 105, "code": "+7 7", "name": "Kazakhstan", "flag": "🇰🇿" },
    { "id": 106, "code": "+254", "name": "Kenya", "flag": "🇰🇪" },
    { "id": 107, "code": "+686", "name": "Kiribati", "flag": "🇰🇮" },
    { "id": 108, "code": "+383", "name": "Kosovo", "flag": "🇽🇰" },
    { "id": 109, "code": "+965", "name": "Kuwait", "flag": "🇰🇼" },
    { "id": 110, "code": "+996", "name": "Kyrgyzstan", "flag": "🇰🇬" },
    { "id": 111, "code": "+856", "name": "Laos", "flag": "🇱🇦" },
    { "id": 112, "code": "+371", "name": "Latvia", "flag": "🇱🇻" },
    { "id": 113, "code": "+961", "name": "Lebanon", "flag": "🇱🇧" },
    { "id": 114, "code": "+266", "name": "Lesotho", "flag": "🇱🇸" },
    { "id": 115, "code": "+231", "name": "Liberia", "flag": "🇱🇷" },
    { "id": 116, "code": "+218", "name": "Libya", "flag": "🇱🇾" },
    { "id": 117, "code": "+423", "name": "Liechtenstein", "flag": "🇱🇮" },
    { "id": 118, "code": "+370", "name": "Lithuania", "flag": "🇱🇹" },
    { "id": 119, "code": "+352", "name": "Luxembourg", "flag": "🇱🇺" },
    { "id": 120, "code": "+853", "name": "Macao SAR", "flag": "🇲🇴" },
    { "id": 121, "code": "+389", "name": "North Macedonia", "flag": "🇲🇰" },
    { "id": 122, "code": "+261", "name": "Madagascar", "flag": "🇲🇬" },
    { "id": 123, "code": "+265", "name": "Malawi", "flag": "🇲🇼" },
    { "id": 124, "code": "+60", "name": "Malaysia", "flag": "🇲🇾" },
    { "id": 125, "code": "+960", "name": "Maldives", "flag": "🇲🇻" },
    { "id": 126, "code": "+223", "name": "Mali", "flag": "🇲🇱" },
    { "id": 127, "code": "+356", "name": "Malta", "flag": "🇲🇹" },
    { "id": 128, "code": "+692", "name": "Marshall Islands", "flag": "🇲🇭" },
    { "id": 129, "code": "+596", "name": "Martinique", "flag": "🇲🇶" },
    { "id": 130, "code": "+222", "name": "Mauritania", "flag": "🇲🇷" },
    { "id": 131, "code": "+230", "name": "Mauritius", "flag": "🇲🇺" },
    { "id": 132, "code": "+262", "name": "Mayotte", "flag": "🇾🇹" },
    { "id": 133, "code": "+52", "name": "Mexico", "flag": "🇲🇽" },
    { "id": 134, "code": "+691", "name": "Micronesia", "flag": "🇫🇲" },
    { "id": 135, "code": "+373", "name": "Moldova", "flag": "🇲🇩" },
    { "id": 136, "code": "+377", "name": "Monaco", "flag": "🇲🇨" },
    { "id": 137, "code": "+976", "name": "Mongolia", "flag": "🇲🇳" },
    { "id": 138, "code": "+382", "name": "Montenegro", "flag": "🇲🇪" },
    { "id": 139, "code": "+1 664", "name": "Montserrat", "flag": "🇲🇸" },
    { "id": 140, "code": "+212", "name": "Morocco", "flag": "🇲🇦" },
    { "id": 141, "code": "+258", "name": "Mozambique", "flag": "🇲🇿" },
    { "id": 142, "code": "+95", "name": "Myanmar", "flag": "🇲🇲" },
    { "id": 143, "code": "+264", "name": "Namibia", "flag": "🇳🇦" },
    { "id": 144, "code": "+674", "name": "Nauru", "flag": "🇳🇷" },
    { "id": 145, "code": "+977", "name": "Nepal", "flag": "🇳🇵" },
    { "id": 146, "code": "+31", "name": "Netherlands", "flag": "🇳🇱" },
    { "id": 147, "code": "+599", "name": "Netherlands Antilles", "flag": "🇳🇱" },
    { "id": 148, "code": "+687", "name": "New Caledonia", "flag": "🇳🇨" },
    { "id": 149, "code": "+64", "name": "New Zealand", "flag": "🇳🇿" },
    { "id": 150, "code": "+505", "name": "Nicaragua", "flag": "🇳🇮" },
    { "id": 151, "code": "+227", "name": "Niger", "flag": "🇳🇪" },
    { "id": 152, "code": "+234", "name": "Nigeria", "flag": "🇳🇬" },
    { "id": 153, "code": "+683", "name": "Niue", "flag": "🇳🇺" },
    { "id": 154, "code": "+850", "name": "North Korea", "flag": "🇰🇵" },
    { "id": 155, "code": "+1 670", "name": "Northern Mariana Islands", "flag": "🇲🇵" },
    { "id": 156, "code": "+47", "name": "Norway", "flag": "🇳🇴" },
    { "id": 157, "code": "+968", "name": "Oman", "flag": "🇴🇲" },
    { "id": 158, "code": "+92", "name": "Pakistan", "flag": "🇵🇰" },
    { "id": 159, "code": "+680", "name": "Palau", "flag": "🇵🇼" },
    { "id": 160, "code": "+970", "name": "Palestinian Territory", "flag": "🇵🇸" },
    { "id": 161, "code": "+507", "name": "Panama", "flag": "🇵🇦" },
    { "id": 162, "code": "+675", "name": "Papua New Guinea", "flag": "🇵🇬" },
    { "id": 163, "code": "+595", "name": "Paraguay", "flag": "🇵🇾" },
    { "id": 164, "code": "+51", "name": "Peru", "flag": "🇵🇪" },
    { "id": 165, "code": "+63", "name": "Philippines", "flag": "🇵🇭" },
    { "id": 166, "code": "+48", "name": "Poland", "flag": "🇵🇱" },
    { "id": 167, "code": "+351", "name": "Portugal", "flag": "🇵🇹" },
    { "id": 168, "code": "+1 787", "name": "Puerto Rico", "flag": "🇵🇷" },
    { "id": 169, "code": "+974", "name": "Qatar", "flag": "🇶🇦" },
    { "id": 170, "code": "+262", "name": "Réunion", "flag": "🇷🇪" },
    { "id": 171, "code": "+40", "name": "Romania", "flag": "🇷🇴" },
    { "id": 172, "code": "+7", "name": "Russia", "flag": "🇷🇺" },
    { "id": 173, "code": "+250", "name": "Rwanda", "flag": "🇷🇼" },
    { "id": 174, "code": "+685", "name": "Samoa", "flag": "🇼🇸" },
    { "id": 175, "code": "+378", "name": "San Marino", "flag": "🇸🇲" },
    { "id": 176, "code": "+239", "name": "São Tomé & Príncipe", "flag": "🇸🇹" },
    { "id": 177, "code": "+966", "name": "Saudi Arabia", "flag": "🇸🇦" },
    { "id": 178, "code": "+221", "name": "Senegal", "flag": "🇸🇳" },
    { "id": 179, "code": "+381", "name": "Serbia", "flag": "🇷🇸" },
    { "id": 180, "code": "+248", "name": "Seychelles", "flag": "🇸🇨" },
    { "id": 181, "code": "+232", "name": "Sierra Leone", "flag": "🇸🇱" },
    { "id": 182, "code": "+65", "name": "Singapore", "flag": "🇸🇬" },
    { "id": 183, "code": "+1 721", "name": "Sint Maarten", "flag": "🇸🇽" },
    { "id": 184, "code": "+421", "name": "Slovakia", "flag": "🇸🇰" },
    { "id": 185, "code": "+386", "name": "Slovenia", "flag": "🇸🇮" },
    { "id": 186, "code": "+677", "name": "Solomon Islands", "flag": "🇸🇧" },
    { "id": 187, "code": "+252", "name": "Somalia", "flag": "🇸🇴" },
    { "id": 188, "code": "+27", "name": "South Africa", "flag": "🇿🇦" },
    { "id": 189, "code": "+82", "name": "South Korea", "flag": "🇰🇷" },
    { "id": 190, "code": "+211", "name": "South Sudan", "flag": "🇸🇸" },
    { "id": 191, "code": "+34", "name": "Spain", "flag": "🇪🇸" },
    { "id": 192, "code": "+94", "name": "Sri Lanka", "flag": "🇱🇰" },
    { "id": 193, "code": "+249", "name": "Sudan", "flag": "🇸🇩" },
    { "id": 194, "code": "+597", "name": "Suriname", "flag": "🇸🇷" },
    { "id": 195, "code": "+47", "name": "Svalbard & Jan Mayen", "flag": "🇸🇯" },
    { "id": 196, "code": "+268", "name": "Swaziland", "flag": "🇸🇿" },
    { "id": 197, "code": "+46", "name": "Sweden", "flag": "🇸🇪" },
    { "id": 198, "code": "+41", "name": "Switzerland", "flag": "🇨🇭" },
    { "id": 199, "code": "+963", "name": "Syria", "flag": "🇸🇾" },
    { "id": 200, "code": "+886", "name": "Taiwan", "flag": "🇹🇼" },
    { "id": 201, "code": "+992", "name": "Tajikistan", "flag": "🇹🇯" },
    { "id": 202, "code": "+255", "name": "Tanzania", "flag": "🇹🇿" },
    { "id": 203, "code": "+66", "name": "Thailand", "flag": "🇹🇭" },
    { "id": 204, "code": "+670", "name": "Timor-Leste", "flag": "🇹🇱" },
    { "id": 205, "code": "+228", "name": "Togo", "flag": "🇹🇬" },
    { "id": 206, "code": "+690", "name": "Tokelau", "flag": "🇹🇰" },
    { "id": 207, "code": "+676", "name": "Tonga", "flag": "🇹🇴" },
    { "id": 208, "code": "+1 868", "name": "Trinidad & Tobago", "flag": "🇹🇹" },
    { "id": 209, "code": "+216", "name": "Tunisia", "flag": "🇹🇳" },
    { "id": 210, "code": "+90", "name": "Turkey", "flag": "🇹🇷" },
    { "id": 211, "code": "+993", "name": "Turkmenistan", "flag": "🇹🇲" },
    { "id": 212, "code": "+1 649", "name": "Turks & Caicos Islands", "flag": "🇹🇨" },
    { "id": 213, "code": "+688", "name": "Tuvalu", "flag": "🇹🇻" },
    { "id": 214, "code": "+1 340", "name": "U.S. Virgin Islands", "flag": "🇻🇮" },
    { "id": 215, "code": "+256", "name": "Uganda", "flag": "🇺🇬" },
    { "id": 216, "code": "+380", "name": "Ukraine", "flag": "🇺🇦" },
    { "id": 217, "code": "+971", "name": "United Arab Emirates", "flag": "🇦🇪" },
    { "id": 218, "code": "+44", "name": "United Kingdom", "flag": "🇬🇧" },
    { "id": 219, "code": "+1", "name": "United States", "flag": "🇺🇸" },
    { "id": 220, "code": "+598", "name": "Uruguay", "flag": "🇺🇾" },
    { "id": 221, "code": "+998", "name": "Uzbekistan", "flag": "🇺🇿" },
    { "id": 222, "code": "+678", "name": "Vanuatu", "flag": "🇻🇺" },
    { "id": 223, "code": "+39", "name": "Vatican City", "flag": "🇻🇦" },
    { "id": 224, "code": "+58", "name": "Venezuela", "flag": "🇻🇪" },
    { "id": 225, "code": "+84", "name": "Vietnam", "flag": "🇻🇳" },
    { "id": 226, "code": "+681", "name": "Wallis & Futuna", "flag": "🇼🇫" },
    { "id": 227, "code": "+967", "name": "Yemen", "flag": "🇾🇪" },
    { "id": 228, "code": "+260", "name": "Zambia", "flag": "🇿🇲" },
    { "id": 229, "code": "+263", "name": "Zimbabwe", "flag": "🇿🇼" }
]
